### ISSUE TITLE
undefined reference to `IRrecv::IRrecv(int)'

### ISSUE THREAD

**Issue by aleksy** [chauhannaman98/ArduinoCodes#1]
`Build options changed, rebuilding all
/tmp/ccurGyHR.ltrans0.ltrans.o: In function `__static_initialization_and_destruction_0':
/home/alex/Arduino/infracrveno/infracrveno.ino:4: undefined reference to `IRrecv::IRrecv(int)'
/tmp/ccurGyHR.ltrans0.ltrans.o: In function `setup':
/home/alex/Arduino/infracrveno/infracrveno.ino:10: undefined reference to `IRrecv::enableIRIn()'
/tmp/ccurGyHR.ltrans0.ltrans.o: In function `loop':
/home/alex/Arduino/infracrveno/infracrveno.ino:15: undefined reference to `IRrecv::decode(decode_results*)'
/home/alex/Arduino/infracrveno/infracrveno.ino:22: undefined reference to `IRrecv::resume()'
collect2: error: ld returned 1 exit status
exit status 1
Error compiling for board Arduino/Genuino Uno.
`
It just doesn't work and the problem is, I don't know how to fix it.
I have followed your instructions on hackster.io

**Comment by chauhannaman98** [comment]
Hello there,

Can you please provide the sketch for minimal reproduction? Also, please check that all the libraries used in the sketch are properly installed and updated. If they are not working well, then, try installing them. That can be a preliminary check for this.
Waiting for your reply!

**Comment by chauhannaman98** [comment]
It's been a week and I haven't got your reply. I have to close this issue for now.
You can ask your query anytime. I'll reopen the issue.
